### ISSUE TITLE
Can't claim rewards

### ISSUE THREAD

**Issue by aspekt19** [koii-network/koii-node#3]
So, what I encountered. I am running the node on an iMac M1. One of the three available tasks does not start, it is "Google-doodle-task", and I also can not unstake the coins I stake to perform the task. The other 2 tasks start, but periodically the task "I'm a Task. Free Tokens!" spontaneously stops, I haven't noticed any pattern as to why this happens while I'm watching. Next, a few times I managed to claim rewards, but then I failed to do so, I will provide screenshots below. After I have claimed the rewards balance is zeroed, but in half a minute the balance of rewards returns to the original at that time. I can assume that this happens because my rewards exceeded the declared bonus.

The first screenshot - the state of the node before claiming rewards.
The second screenshot - just after claiming.
The third screenshot - a minute after claiming.
<img width="1173" alt="Снимок экрана 2023-05-14 в 12 40 00" src="https://github.com/koii-network/desktop-node/assets/36282486/aec9ecf7-59cf-45ac-b2e0-20bea2d423e6">
<img width="1211" alt="Снимок экрана 2023-05-14 в 12 48 07" src="https://github.com/koii-network/desktop-node/assets/36282486/e5bae568-13b6-475b-950a-dac3dd70495e">
<img width="1178" alt="Снимок экрана 2023-05-14 в 13 02 14" src="https://github.com/koii-network/desktop-node/assets/36282486/d3ae748b-dd77-4170-84d1-39720b99e5e4">

**Comment by smith-and-web** [comment]
Hey! Thanks for reporting. We made a fresh set of binaries last night which should address a lot of these issues. 

A couple more things to note: the google doodle task is not updated and has been blacklisted so people can't stake. We are aware that there seems to be an issue unstaking on blacklisted tasks and we're working on that.

In the meantime check out the [Releases](https://github.com/koii-network/desktop-node/releases) and download your OS install there. Same version number but should have these fixes in it. Updates going forward will be through auto updating if you're using macos or a linux AppImage.
